---
title: "hw03"
author: "Eriko Funasato"
date: "October 15, 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(dplyr)
dat1 <- read.csv("../data/nba2017-roster.csv")
dat2 <- read.csv("../data/nba2017-stats.csv")

#Adding new variables
dat2 <- mutate(dat2,missed_fg=dat2$field_goals_atts - dat2$field_goals_made, 
               missed_ft=dat2$points1_atts-dat2$points1_made,
               points= 3*dat2$points3_made +2*dat2$points2_made+dat2$points1_made,
               rebounds = dat2$off_rebounds + dat2$def_rebounds,
               efficiency= (points+rebounds+dat2$assist+dat2$steals+
                              dat2$blocks- missed_fg - missed_ft - dat2$turnovers)
               /dat2$games_played)
sink(file = "../output/efficiency-summary.txt")
summary(dat2)
sink()
#Merging Tables
dat <- merge(dat1,dat2)
colnames(dat)[20] <- "free_throws"

#Creating nba2017-teams.csv
team <- summarize(group_by(dat,team),Experience=round(sum(experience),digits = 2),
                  Salary=sum(round(salary*(10^-6),digits = 2)),
                  Points3=sum(points3_made),Points2=sum(points2_made),
                  Free_throws=sum(free_throws),Points=sum(points),
                  Off_rebounds=sum(off_rebounds),Def_rebounds=sum(def_rebounds),
                  Assists=sum(assists),Steals=sum(steals),Blocks=sum(blocks),
                  Turnovers=sum(turnovers),Fouls=sum(fouls),
                  Efficiency=sum(efficiency))
```

#Ranking of Teams
```{r}
library(ggplot2)
#Basic Rankings
#Use ggplot() to create a barchart (horizontally oriented) The vertical red line is the average team salary.
ggplot(data=team,aes(x=reorder(team,Salary),y=Salary))+geom_bar(stat='identity',fill='grey')+coord_flip()+geom_hline(aes(yintercept=90.95),col='red')+labs(y="Salary(in millions)")+labs(x="teams")+ggtitle("NBA Teams ranked by Total Salary")

```
```{r}
#Create another bar chart of teams ranked by total points. The vertical red line is the average team points
ggplot(data=team,aes(x=reorder(team,Points),y=Points))+geom_bar(stat='identity',fill='grey')+coord_flip()+geom_hline(aes(yintercept=mean(Points)),col='red')+labs(y="Total Points")+labs(x="teams")+ggtitle("NBA Teams ranked by Total Points")
```
```{r}
#Use efficiency to obtain a third kind of ranking, and create an associated bar chart of teams ranked by total efficiency. The vertical red line is the average team efficiency.
ggplot(data=team,aes(x=reorder(team,Efficiency),y=Efficiency))+geom_bar(stat='identity',fill='grey')+coord_flip()+geom_hline(aes(yintercept=mean(Efficiency)),col='red')+labs(y="Total Efficiency")+labs(x="teams")+ggtitle("NBA Teams ranked by Total Efficiency")
```

#Principal Components Analysis (PCA)
```{r}
#Index based on PC1
PC <- prcomp(team[,2:15],scale=TRUE)
z1 <- PC$x[,1]
s1 <- 100*(z1-min(z1))/(max(z1)-min(z1))
#barchart
ggplot(data=team,aes(x=reorder(team,s1),y=s1))+geom_bar(stat='identity',fill='grey')+coord_flip()+labs(y="first pc(scaled from 0 to 100")+labs(x="teams")+ggtitle("NBA Teams ranked by scaled PC1")
```




